ujm_category_create_pop:
    pattern: /category/create_pop
    defaults: { _controller: UJMExoBundle:Category:createPop }
    requirements:
      _method: POST
    
ujm_category_new_pop:
    pattern:  /category/new_pop
    defaults: { _controller: UJMExoBundle:Category:newPop }
    
ujm_exercise_open:
   pattern: /open/{exerciseId}
   defaults: { _controller: UJMExoBundle:Exercise:open }
   
ujm_question_index:
    pattern: /question/index
    defaults: { _controller: UJMExoBundle:Question:index }
    
ujm_question_new:
    pattern:  /question/new/{exoID}
    defaults: { _controller: UJMExoBundle:Question:new, exoID: -1 }
    
ujm_question_dispaly_form_type:
    pattern: /question/choixFormType
    defaults: { _controller: UJMExoBundle:Question:choixFormType }
    requirements:
      _method: POST
      
ujm_interactiongraphic_create:
    pattern:  /question/InteractionGraphic/create
    defaults: { _controller: "UJMExoBundle:InteractionGraphic:create" }
    requirements: { _method: post }
    
ujm_interactiongraphic_AjoutImg:
    pattern:  /question/InteractionGraphic/AjoutImg
    defaults: { _controller: "UJMExoBundle:WSRest:postDocumentAdd" }
    requirements: { _method: post }
    
ujm_interactiongraphic_SavePic:
    pattern:  /question/InteractionGraphic/SavePic
    defaults: { _controller: "UJMExoBundle:InteractionGraphic:SavePic" }
    
ujm_interactiongraphic_DisplayPic:
    pattern:  /question/InteractionGraphic/DisplayPic
    defaults: { _controller: "UJMExoBundle:InteractionGraphic:DisplayPic" }
    requirements:
      _method: POST