ujm_category_create_pop:
    pattern: /category/create_pop
    defaults: { _controller: UJMExoBundle:Category:createPop }
    requirements:
      _method: POST
    
ujm_category_new_pop:
    pattern:  /category/new_pop
    defaults: { _controller: UJMExoBundle:Category:newPop }
    
ujm_exercise_open:
   pattern: /open/{exerciseId}
   defaults: { _controller: UJMExoBundle:Exercise:open }
   
ujm_interactionqcm_create:
    pattern:  /interactionqcm/create
    defaults: { _controller: "UJMExoBundle:InteractionQCM:create" }
    requirements: { _method: post }
    
ujm_interactionqcm_response:
    pattern: /testQCM
    defaults: { _controller: "UJMExoBundle:InteractionQCM:responseQcm" }
    requirements: { _method: post }

ujm_interactionqcm_update:
    pattern:  /{id}/update
    defaults: { _controller: "UJMExoBundle:InteractionQCM:update" }
    requirements: { _method: post }
   
ujm_question_index:
    pattern: /question/index
    defaults: { _controller: UJMExoBundle:Question:index }
    
ujm_question_show:
    pattern:  /{id}/show
    defaults: { _controller: "UJMExoBundle:Question:show" }
    
ujm_question_new:
    pattern:  /question/new/{exoID}
    defaults: { _controller: UJMExoBundle:Question:new, exoID: -1 }
    
ujm_question_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UJMExoBundle:Question:edit" }
    
ujm_question_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UJMExoBundle:Question:delete" }
    requirements: { _method: post }
    
ujm_question_dispaly_form_type:
    pattern: /question/choixFormType
    defaults: { _controller: UJMExoBundle:Question:choixFormType }
    requirements:
      _method: POST
      
ujm_question_show:
    pattern:  /question/show/{id}
    defaults: { _controller: "UJMExoBundle:Question:show" }
      
ujm_interactiongraphic_create:
    pattern:  /question/InteractionGraphic/create
    defaults: { _controller: "UJMExoBundle:InteractionGraphic:create" }
    requirements: { _method: post }
    
ujm_interactiongraphic_AjoutImg:
    pattern:  /question/InteractionGraphic/AjoutImg
    defaults: { _controller: "UJMExoBundle:WSRest:postDocumentAdd" }
    requirements: { _method: post }
    
ujm_interactiongraphic_SavePic:
    pattern:  /question/InteractionGraphic/SavePic
    defaults: { _controller: "UJMExoBundle:InteractionGraphic:savePic" }
    
ujm_interactiongraphic_DisplayPic:
    pattern:  /question/InteractionGraphic/DisplayPic
    defaults: { _controller: "UJMExoBundle:InteractionGraphic:displayPic" }
    requirements:
      _method: POST

ujm_hint_show:
    pattern:  /question/hint/show
    defaults: { _controller: "UJMExoBundle:Hint:show" }
    requirements: { _method: post }

ujm_interactiongraphic_response:
    pattern: /testGraphic
    defaults: { _controller: "UJMExoBundle:InteractionGraphic:responseGraphic" }