services:
    ujm.listener.exercise_listener:
        class: UJM\ExoBundle\Listener\ExerciseListener
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.event_listener, event: create_form_ujm_exercise, method: onCreateForm }
            - { name: kernel.event_listener, event: create_ujm_exercise, method: onCreate }
            - { name: kernel.event_listener, event: open_ujm_exercise, method: onOpen }
#      - { name: kernel.event_listener, event: export_ujm_exercise, method: onExport }
            - { name: kernel.event_listener, event: delete_ujm_exercise, method: onDelete }
            - { name: kernel.event_listener, event: copy_ujm_exercise, method: onCopy }
#      - { name: kernel.event_listener, event: plugin_options_ujmexo, method: onAdministrate }
            - { name: kernel.event_listener, event: open_tool_desktop_ujm_questions, method: onDisplayDesktop}

    ujm.listener.exercise.display_log_listener:
            class: UJM\ExoBundle\Listener\Log\DisplayLogListener
            calls:
                - [setContainer, ["@service_container"]]
            tags:
                - { name: kernel.event_listener, event: create_log_details_resource-ujm_exercise-exercise_evaluated, method: onCreateLogDetails }

    twig.extension.twigExtensions:
        class: UJM\ExoBundle\Services\twig\twigExtensions
        arguments: [@doctrine, @ujm.exercise_services]
        tags:
            - { name: twig.extension }

    ujm.exercise_services:
        class: UJM\ExoBundle\Services\classes\exerciseServices
        arguments: [@doctrine, @security.context, @event_dispatcher]

#    ujm.qti_service:
#        class: UJM\ExoBundle\Services\classes\qtiService
#        arguments: [@doctrine, @security.context]

    ujm.qti_qcm_export:
        class: UJM\ExoBundle\Services\classes\QTI\qcmExport
        arguments: [@doctrine, @security.context, @service_container]

    ujm.qti_graphic_export:
        class: UJM\ExoBundle\Services\classes\QTI\graphicExport
        arguments: [@doctrine, @security.context, @service_container]

    ujm.exercise.validator.isvalidqcmglobalmark:
        class: UJM\ExoBundle\Validator\Constraints\isValidQCMGlobalMarkValidator
        arguments: [@request]
        scope: request
        tags:
            - { name: validator.constraint_validator, alias: ujm.exercise_isvalidqcmglobalmark }

    ujm.exercise.validator.isvalidqcmmark:
        class: UJM\ExoBundle\Validator\Constraints\isValidQCMMarkValidator
        arguments: [@request]
        scope: request
        tags:
            - { name: validator.constraint_validator, alias: ujm.exercise_isvalidqcmmark }