ujm_exercise_delete_all_paper:
    pattern:  /delete/all/paper/{id}
    defaults: { _controller: "UJMExoBundle:Exercise:deleteAllPapers" }

ujm_exercise_docimology:
     pattern:  /docimology/{exerciseId}/{nbPapers}
     defaults: { _controller: "UJMExoBundle:Exercise:docimology" }

ujm_exercise_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UJMExoBundle:Exercise:edit" }

ujm_exercise_import_question:
    pattern: /{exoID}/import/{pageGoNow}/{maxPage}/{nbItem}/{displayAll}/{idExo}/{QuestionsExo}
    defaults: { _controller: UJMExoBundle:Exercise:importQuestion, pageGoNow: 1, maxPage: 10, nbItem: 1, displayAll: 0, idExo: -1, QuestionsExo: false }

ujm_exercise_publish:
    pattern:  /publish
    defaults: { _controller: "UJMExoBundle:Exercise:publish" }
    requirements:
      _method: POST

ujm_exercise_unpublish:
    pattern:  /unpublish
    defaults: { _controller: "UJMExoBundle:Exercise:unpublish" }
    requirements:
      _method: POST

ujm_exercise_questions:
    pattern:  /{id}/questions/{pageNow}/{categoryToFind}/{titleToFind}/{displayAll}
    defaults: { _controller: UJMExoBundle:Exercise:showQuestions, pageNow: 0, categoryToFind: z, titleToFind: z, displayAll: 0 }
    requirements:
        categoryToFind: ".+"
        titleToFind: ".+"

ujm_exercise_question_delete:
    pattern:  /{exoID}/{qid}/delete/{pageNow}/{maxPage}/{nbItem}/{lastPage}
    defaults: { _controller: UJMExoBundle:Exercise:deleteQuestion, pageNow: 1, maxPage: 10, nbItem: 1, lastPage: 1 }

ujm_exercise_update:
    pattern:  /{id}/update
    defaults: { _controller: "UJMExoBundle:Exercise:update" }
    requirements: { _method: post }

ujm_exercise_validate_import:
    pattern: /import
    defaults: { _controller: "UJMExoBundle:Exercise:importValidate" }

ujm_exercise_question_order:
    pattern:  /ExerciseQuestion/changeOrder
    defaults: { _controller: "UJMExoBundle:Exercise:changeQuestionOrder" }
    requirements: { _method: post }