ujm_question_index:
    pattern: /index
    defaults: { _controller: UJMExoBundle:Question:index }

ujm_question_show:
    pattern:  /{id}/show
    defaults: { _controller: "UJMExoBundle:Question:show" }

ujm_question_new:
    pattern:  /new/{exoID}
    defaults: { _controller: UJMExoBundle:Question:new, exoID: -1 }

ujm_question_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UJMExoBundle:Question:edit" }

ujm_question_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UJMExoBundle:Question:delete" }
    requirements: { _method: post }

ujm_question_dispaly_form_type:
    pattern: /choixFormType
    defaults: { _controller: UJMExoBundle:Question:choixFormType }
    requirements:
      _method: POST

ujm_question_share:
  pattern: /share/{questionID}
  defaults: { _controller: "UJMExoBundle:Question:share" }

ujm_question_share_search_user:
  pattern: /share/search/user
  defaults: { _controller: "UJMExoBundle:Question:search" }
  requirements:
      _method: POST

ujm_question_show:
    pattern:  /show/{id}
    defaults: { _controller: "UJMExoBundle:Question:show" }

ujm_question_manage_doc:
    pattern:  /manageDoc
    defaults: { _controller: "UJMExoBundle:Question:manageDoc" }

ujm_document_del:
    pattern:  /deleteDoc/{label}
    defaults: { _controller: "UJMExoBundle:Question:deleteDoc" }

ujm_document_del_linked:
    pattern:  /deletelinkedDoc/{label}
    defaults: { _controller: "UJMExoBundle:Question:deletelinkedDoc" }

ujm_question_name_update:
    pattern: /update/name
    defaults: { _controller: "UJMExoBundle:Question:updateName" }
    requirements:
        _method: POST

ujm_question_sortDocuments:
    pattern: /sort
    defaults: { _controller: "UJMExoBundle:Question:sortDocuments" }
    requirements:
        _method: POST

ujm_question_searchDocuments:
    pattern: /search
    defaults: { _controller: "UJMExoBundle:Question:searchDoc" }
    requirements:
        _method: POST

ujm_question_shareQuestionUser:
    pattern: /shareQuestionUser
    defaults: { _controller: "UJMExoBundle:Question:shareQuestionUser" }
    requirements:
        _method: POST