ujm_qti_import:
    pattern:  /import
    defaults: { _controller: UJMExoBundle:Qti:import }

ujm_qti_import_form:
    pattern:  /import/form
    defaults: { _controller: UJMExoBundle:Qti:importForm }